name = "sinskey"
main = "_worker.js"
compatibility_date = "2025-10-08"
compatibility_flags = ["nodejs_compat_v2"]

account_id = "3aff07c04b04ab6d34dfda2f69a1e801"
workers_dev = true

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
